/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package securitydevice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Scanner;

class AppTest {
    @Test
    void test_that_readInput_returns_the_digit_supplied() {
        App app = new App();
        String str = "1";
        Scanner sc = new Scanner(str);
        assertEquals(1, app.readInput(sc));
        sc.close();
    }
    
    @Test
    void test_that_readInput_ignores_non_digits() {
        App app = new App();
        String str = "a bcd e 2";
        Scanner sc = new Scanner(str);
        assertEquals(2, app.readInput(sc));
        sc.close();
    }
}

